routes/web.php
<?php

use App\Http\Controllers\AdminPageController;
use App\Http\Controllers\FileController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [UserPageController::class, 'index'])->name('home_index');

Route::middleware([
    'auth',
    config('jetstream.auth_session'),
    'verified',
])->group(function () {
    Route::get('/dashboard', [UserPageController::class, 'dashboard'])->name('dashboard')->middleware(['role:member|editor']);

    Route::name('admin.')->prefix('admin')->group(function () {
        Route::middleware(['role:super-admin|admin'])->group(function () {
            Route::get('', [AdminPageController::class, 'index']);
            Route::get('dashboard', [AdminPageController::class, 'dashboard'])->name('dashboard');
            Route::get('users', [AdminPageController::class, 'users'])->name('users');
            Route::get('companies', [AdminPageController::class, 'companies'])->name('companies');
            Route::resource('users', UserController::class)->only('create', 'show', 'edit', 'destroy');
        });

        Route::get('/permissions', [AdminPageController::class, 'permissions'])->name('permissions')->middleware(['role:super-admin']);
    });

    // Route::get('/permissions', [RolesAndPermissionsController::class, 'index'])->name('showAssignedRoles');
    // Route::post('/assign_role', [RolesAndPermissionsController::class, 'store'])->name('assignRole');
    // Route::delete('/revoke_role', [RolesAndPermissionsController::class, 'destroy'])->name('revokeRole');

    Route::resource('files', FileController::class)->only('index', 'create', 'show', 'edit', 'destroy');
});

resources/views/admin/companies.blade.php
<x-app-layout :title="'Companies'">
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">
            {{ __('Companies') }}
        </h2>
    </x-slot>

    <div class="px-4 py-3">
        <div class="mx-auto max-w-full sm:px-3 lg:px-4">
            <div class="overflow-hidden bg-white px-2 py-3 shadow-xl dark:bg-gray-800 sm:rounded-lg">
                @livewire('company.table')
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/dashboard.blade.php
<x-app-layout :title="'Dashboard'">
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">
            {{ __('Dashboard admin') }}
        </h2>
    </x-slot>

    <div class="px-4 py-3">
        <div class="mb-6 pt-1">
            <div class="-mx-2 flex flex-wrap">
                @include('components.card', [
                    'icon' => 'forkawesome-file-o',
                    'color' => 'slate',
                    'text_one' => __('Files'),
                    'text_two' => $fileCount,
                ])
                @include('components.card', [
                    'icon' => 'forkawesome-download',
                    'color' => 'green',
                    'text_one' => __('Downloads'),
                    'text_two' => $fileDownloads,
                ])
                @include('components.card', [
                    'icon' => 'forkawesome-commenting-o',
                    'color' => 'orange',
                    'text_one' => __('Comments'),
                    'text_two' => $commentCount,
                ])
                @include('components.card', [
                    'icon' => 'forkawesome-user',
                    'icon_class' => 'w-10 ml-2',
                    'icon_padding' => 'py-4 pl-3 pr-3',
                    'color' => 'blue',
                    'text_one' => __('Users'),
                    'text_two' => $userCount,
                ])
            </div>
        </div>
        <div class="mx-auto max-w-full sm:px-3 lg:px-4">
            <div class="px-2">
                <div class="-mx-2 flex">
                    <div class="w-1/2 px-2">
                        <div class="bg-white shadow-xl dark:bg-gray-800">
                            <p class="mb-1 mt-2 px-4 text-center text-3xl font-black text-gray-900 dark:text-gray-300">
                                {{ __('Latest uploaded files') }}</p>
                            @livewire('file.simpletable')
                        </div>
                    </div>
                    <div class="w-1/2 px-2">
                        <div class="bg-white shadow-xl dark:bg-gray-800">
                            <p class="mb-1 mt-2 px-4 text-center text-3xl font-black text-gray-900 dark:text-gray-300">
                                {{ __('Latest users') }}</p>
                            @livewire('user.simpletable')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/permissions.blade.php
<x-app-layout :title="'Permissions'">
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">
            {{ __('Permissions') }}
        </h2>
    </x-slot>

    <div class="px-4 py-3">
        <div class="mx-auto max-w-full sm:px-3 lg:px-4">
            <div class="overflow-hidden px-2 pt-3 shadow-xl sm:rounded-lg">
                <div class="pb-6" x-data="{
                    activeTab: 1,
                    activeClass: 'border-gray-100 dark:border-gray-700 border-l-2 border-t-4 border-r-2 text-gray-800 dark:text-gray-200 border-t-indigo-400 dark:border-t-indigo-600 focus:outline-none focus:border-t-indigo-700 transition duration-150 ease-in-out',
                    inactiveClass: 'text-gray-600 dark:text-gray-400 hover:text-gray-500'
                }">
                    <ul class="flex justify-center border-b-2 border-gray-100 dark:border-gray-700">
                        <li :class="{ '-mb-0.5': activeTab === 1 }">
                            <a class="inline-block bg-white px-4 py-2 text-xl font-semibold dark:bg-gray-800"
                                href="#" x-on:click="activeTab = 1"
                                :class="activeTab === 1 ? activeClass : inactiveClass">Roles</a>
                        </li>
                        <li :class="{ '-mb-0.5': activeTab === 2 }">
                            <a class="inline-block bg-white px-4 py-2 text-xl font-semibold dark:bg-gray-800"
                                href="#" x-on:click="activeTab = 2"
                                :class="activeTab === 2 ? activeClass : inactiveClass">Permissions</a>
                        </li>
                    </ul>
                    <div class="w-full bg-white p-6 text-gray-800 dark:bg-gray-800 dark:text-gray-200">
                        <div x-show="activeTab === 1">
                            @livewire('role.table')
                        </div>
                        <div x-show="activeTab === 2">
                            @livewire('permission.table')
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/admin/users.blade.php
<x-app-layout :title="'Users'">
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800 dark:text-gray-200">
            {{ __('Users') }}
        </h2>

        <a class="btn ml-auto" href="{{ route('admin.users.create') }}">
            {{ __('New') }}
        </a>
    </x-slot>

    <div class="px-4 py-3">
        <div class="mx-auto max-w-full sm:px-3 lg:px-4">
            <div class="overflow-hidden bg-white px-2 py-3 shadow-xl dark:bg-gray-800 sm:rounded-lg">
                @livewire('user.table')
            </div>
        </div>
    </div>
</x-app-layout>